kramdown:
  math_engine: mathjax
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Rouge Options: https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  art:
    output: true
    sort_by: date
  projects:
    output: true
    sort_by: date